version: '3.7'

services:
  mongo_db:
    container_name: mongo_db
    restart: always
    image: mongo
    env_file:
      - ./.mongo.dev.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
    ports:
      - 27016:27017

  ai_predicet:
    container_name: AiPredicet
    restart: always
    build:
      dockerfile: ./Dockerfile
    env_file:
      - ./.service.dev.env
    environment:
      PORT: ${PORT}
      MONGO_URL: ${MONGO_URL}
      MONGO_DATANAME: ${MONGO_DATANAME}
      MONGO_COLLECTION_NAME: ${MONGO_COLLECTION_NAME}
      API_SECRET: ${API_SECRET}
      API_KEY: ${API_KEY}
    ports:
      - 50051:50051
